name: Azure Functions Deploy

on:
  push:
    branches:
      - main  # ou a branch que você deseja monitorar

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Certifique-se de usar a versão correta do Node.js

    - name: Install dependencies
      run: npm install

    - name: Archive functions folder
      run: zip -r functions.zip .

    - name: Deploy to Azure Functions
      uses: azure/functions-action@v1
      with:
        app-name: YOUR_FUNCTION_APP_NAME
        package: functions.zip
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
